### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by impredicative** [github/annotated-logger#34]
1. The PyPI package name https://pypi.org/project/annotated-logger/ isn't documented in the readme.
2. The informative article https://github.blog/developer-skills/programming-languages-and-frameworks/introducing-annotated-logger-a-python-package-to-aid-in-adding-metadata-to-logs/ isn't linked in the readm.
3. There is a lot that is covered in the above-linked article that isn't in the readme.

**Comment by crimsonknave** [comment]
Thanks for pointing it out! I wrote both at very different stages in the process and lost track of how different they were. I pulled over almost all of the content in #35 I think the only things I left were some more introduction type content that I think was already covered in the README.
